#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

// AtomEchoS3R Board configuration
// Verdure Buddy Rover variant: 增加 1.47" ST7789 172x320 屏幕 + Grove 串口控制

#include <driver/gpio.h>

#define AUDIO_INPUT_REFERENCE true
#define AUDIO_INPUT_SAMPLE_RATE 24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_11
#define AUDIO_I2S_GPIO_WS GPIO_NUM_3
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_17
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_4
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_48

#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_45
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_0
#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_GPIO_PA GPIO_NUM_18

#define BUILTIN_LED_GPIO GPIO_NUM_NC
#define USER_BUTTON_GPIO GPIO_NUM_41
#define VOLUME_UP_BUTTON_GPIO GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

// ---- Display: 1.47" ST7789 172x320 SPI (底部 GPIO G5/G6/G7/G8/G38/G39) ----
#define DISPLAY_CS_PIN GPIO_NUM_5
#define DISPLAY_MOSI_PIN GPIO_NUM_6
#define DISPLAY_SCLK_PIN GPIO_NUM_7
#define DISPLAY_DC_PIN GPIO_NUM_8
#define DISPLAY_RESET_PIN GPIO_NUM_38
#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_39

#define DISPLAY_SPI_SCLK_HZ (40 * 1000 * 1000)
#define DISPLAY_SPI_MODE 0

#define LCD_TYPE_ST7789_SERIAL
#define DISPLAY_WIDTH 172
#define DISPLAY_HEIGHT 320
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR true
#define DISPLAY_RGB_ORDER LCD_RGB_ELEMENT_ORDER_BGR
#define DISPLAY_OFFSET_X 34
#define DISPLAY_OFFSET_Y 0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

// ---- Serial command control (Grove G1/G2 = GPIO1/GPIO2) ----
#define SERIAL_CONTROL_TX_PIN GPIO_NUM_1  // G1
#define SERIAL_CONTROL_RX_PIN GPIO_NUM_2  // G2
#define SERIAL_CONTROL_BAUD 115200

#endif  // _BOARD_CONFIG_H_
